services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: football_manager_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: football_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kasasa3843
    ports:
     - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - football_manager_network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: football_manager_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:Kasasa3843@postgres:5432/football_manager
      CORS_ORIGINS: http://srv887319.hstgr.cloud:3000
    volumes:
      - ./backend:/app
      - /app/__pycache__
    networks:
      - football_manager_network
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: football_manager_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://srv887319.hstgr.cloud:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - football_manager_network
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
    stop_grace_period: 30s

volumes:
  postgres_data:

networks:
  football_manager_network:
    driver: bridge
